---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:20.04

    steps:
      - run: &apt_install
          apt update &&
          export DEBIAN_FRONTEND=noninteractive ; apt install -y --no-install-recommends
            cmake
            sudo
            gcc g++
            libconfig-dev
            libgtest-dev
            ninja-build
            pkg-config
            zip grep file ca-certificates autotools-dev autoconf automake
            git bc wget rsync cmake make pkg-config libtool
            ssh gzip tar unzip
            coreutils
            expect
            astyle

      - checkout

      - run: &apt_install
          export DEBIAN_FRONTEND=noninteractive ; apt install -y --no-install-recommends clang-11
      - run: dpkg -l | grep clang
      - run: type -a clang-11
      - run: clang-11 --version


      - run: clang-11 -O3 -g -Wall -Wextra -pedantic
            -Wvla
            -Werror=div-by-zero
            -D LINUX
            pwstore.c -o pwstore

# ---- install ----
      - run: sudo mkdir -p /opt/pwstore
      - run: sudo chmod a+rx /opt/pwstore
      - run: sudo chmod u+rwx /opt/pwstore
      - run: sudo chmod og-w /opt/pwstore

      - run: sudo mkdir -p /opt/pwstore/bin
      - run: sudo chmod u+rwx /opt/pwstore/bin
      - run: sudo chmod og-rw /opt/pwstore/bin
      - run: sudo chmod og+x /opt/pwstore/bin

      - run: sudo mkdir -p /opt/pwstore/conf
      - run: sudo chmod u+rwx /opt/pwstore/conf
      - run: sudo chmod og-rwx /opt/pwstore/conf

      - run: sudo cp -av pwstore /opt/pwstore/bin/pwstore
      - run: sudo chown root:root /opt/pwstore/bin/pwstore
      - run: sudo chmod og-rw /opt/pwstore/bin/pwstore
      - run: sudo chmod og+x /opt/pwstore/bin/pwstore
      - run: sudo chmod u+rwx /opt/pwstore/bin/pwstore
      - run: sudo chmod u+s /opt/pwstore/bin/pwstore

      - run: sudo ls -ald /opt/pwstore
      - run: sudo ls -alR /opt/pwstore
# ---- install ----


      - store_artifacts:
          path: ~/work/pwstore
          destination: pwstore.am64.linux
